--------------------------------------------------------
--  File created - Segunda-feira-Maio-17-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABRANGIDAS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."ABRANGIDAS" 
   (	"ID_PROFISSAO" NUMBER(*,0), 
	"ID_CRITERIOS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARMAZENS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."ARMAZENS" 
   (	"ID_ARMAZEM" NUMBER(*,0), 
	"MORADA" VARCHAR2(1024 BYTE), 
	"DISTRITO" VARCHAR2(1024 BYTE), 
	"REGIAO" VARCHAR2(1024 BYTE), 
	"CAPACIDADE_MAXIMA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAUSAM
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."CAUSAM" 
   (	"ID_TOMA" NUMBER(*,0), 
	"ID_REACOES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CENTRO_SAUDE
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."CENTRO_SAUDE" 
   (	"ID_CENTROSAUDE" NUMBER(*,0), 
	"NOME" VARCHAR2(1024 BYTE), 
	"MORADA" VARCHAR2(1024 BYTE), 
	"CONCELHO" VARCHAR2(1024 BYTE), 
	"TELEMOVEL" NUMBER(*,0), 
	"REGIAO" VARCHAR2(1024 BYTE), 
	"CODIGO_POSTAL" VARCHAR2(50 BYTE), 
	"CIDADE" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CENTROS_VACINACAO
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."CENTROS_VACINACAO" 
   (	"ID_CENTRO" NUMBER(*,0), 
	"MORADA" VARCHAR2(1024 BYTE), 
	"REGIAO" VARCHAR2(1024 BYTE), 
	"CONCELHO" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONVOCATORIAS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."CONVOCATORIAS" 
   (	"ID_CONVOCATORIA" NUMBER(*,0), 
	"ID_FASE" NUMBER(*,0), 
	"ID_SLOT" NUMBER(*,0), 
	"CC" NUMBER(*,0), 
	"JUSTIFICACAO" VARCHAR2(1024 BYTE), 
	"DATACONVOCATORIA" DATE, 
	"RESPOSTA" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CRITERIOS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."CRITERIOS" 
   (	"ID_CRITERIOS" NUMBER(*,0), 
	"ID_FASE" NUMBER(*,0), 
	"INTERVALO_IDADE_INF" NUMBER(*,0), 
	"INTERVALO_IDADE_SUP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOENCAS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."DOENCAS" 
   (	"ID_DOENCAS" NUMBER(*,0), 
	"ID_CRITERIOS" NUMBER(*,0), 
	"NOME" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DOSES
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."DOSES" 
   (	"ID_DOSE" NUMBER(*,0), 
	"ID_FRASCO" NUMBER(*,0), 
	"ESTADO" VARCHAR2(1024 BYTE), 
	"DATA_DA_DOSE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENFERMEIROS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."ENFERMEIROS" 
   (	"CC" NUMBER(*,0), 
	"ID_ENFERMEIRO" NUMBER(*,0), 
	"ID_CENTROSAUDE" NUMBER(*,0), 
	"NOME" VARCHAR2(1024 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"MORADA" VARCHAR2(1024 BYTE), 
	"CODIGO_POSTAL" VARCHAR2(1024 BYTE), 
	"CONCELHO" VARCHAR2(1024 BYTE), 
	"CIDADE" VARCHAR2(1024 BYTE), 
	"REGIAO" VARCHAR2(1024 BYTE), 
	"TELEMOVEL" NUMBER(*,0), 
	"EMAIL" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXERCEM
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."EXERCEM" 
   (	"ID_PROFISSAO" NUMBER(*,0), 
	"CC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FASES
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."FASES" 
   (	"ID_FASE" NUMBER(*,0), 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"NUMERO_FASE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FRASCOS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."FRASCOS" 
   (	"ID_FRASCO" NUMBER(*,0), 
	"ID_TRANSPORTE" NUMBER(*,0), 
	"ID_LOTE" NUMBER(*,0), 
	"LOCALIZACAO" VARCHAR2(1024 BYTE), 
	"DATA_DE_ABERTURA" DATE, 
	"ESTADO" VARCHAR2(1024 BYTE), 
	"DATA_PRODUCAO" DATE, 
	"VALIDADE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INCLUEM
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."INCLUEM" 
   (	"ID_CRITERIOS" NUMBER(*,0), 
	"ID_LOCALPROF" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCAIS_DE_TRABALHO
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."LOCAIS_DE_TRABALHO" 
   (	"ID_LOCALPROF" NUMBER(*,0), 
	"LOCAL_TRABALHO" VARCHAR2(1024 BYTE), 
	"TIPO" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOTES_DAS_VACINAS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."LOTES_DAS_VACINAS" 
   (	"ID_LOTE" NUMBER(*,0), 
	"ID_VACINA" NUMBER(*,0), 
	"ID_ARMAZEM" NUMBER(*,0), 
	"QUANTIDADE" NUMBER(*,0), 
	"DATA_PRODUCAO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORIGINARAM
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."ORIGINARAM" 
   (	"ID_REACOES" NUMBER(*,0), 
	"ID_VACINA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PESSOAS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."PESSOAS" 
   (	"CC" NUMBER(*,0), 
	"ID_CENTROSAUDE" NUMBER(*,0), 
	"NOME" VARCHAR2(1024 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"MORADA" VARCHAR2(1024 BYTE), 
	"CODIGO_POSTAL" VARCHAR2(1024 BYTE), 
	"CONCELHO" VARCHAR2(1024 BYTE), 
	"CIDADE" VARCHAR2(1024 BYTE), 
	"REGIAO" VARCHAR2(1024 BYTE), 
	"TELEMOVEL" NUMBER(*,0), 
	"EMAIL" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PODEM_GUARDAR
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."PODEM_GUARDAR" 
   (	"ID_VACINA" NUMBER(*,0), 
	"ID_ARMAZEM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PODEM_TER
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."PODEM_TER" 
   (	"ID_DOENCAS" NUMBER(*,0), 
	"CC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFISSOES
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."PROFISSOES" 
   (	"ID_PROFISSAO" NUMBER(*,0), 
	"PROFISSAO" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REACOES
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."REACOES" 
   (	"ID_REACOES" NUMBER(*,0), 
	"AVALIACAO" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESPONSAVEIS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."RESPONSAVEIS" 
   (	"ID_TURNO" NUMBER(*,0), 
	"ID_ENFERMEIRO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SLOTS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."SLOTS" 
   (	"ID_SLOT" NUMBER(*,0), 
	"ID_TURNO" NUMBER(*,0), 
	"HORA_ESCOLHIDA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TOMAS_DA_VACINA
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."TOMAS_DA_VACINA" 
   (	"ID_TOMA" NUMBER(*,0), 
	"ID_CONVOCATORIA" NUMBER(*,0), 
	"ID_DOSE" NUMBER(*,0), 
	"DATATOMA" DATE, 
	"DOSE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRABALHAM
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."TRABALHAM" 
   (	"ID_LOCALPROF" NUMBER(*,0), 
	"CC" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSPORTES
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."TRANSPORTES" 
   (	"ID_TRANSPORTE" NUMBER(*,0), 
	"ID_CENTRO" NUMBER(*,0), 
	"ID_ARMAZEM" NUMBER(*,0), 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TURNOS_DE_VACINACAO
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."TURNOS_DE_VACINACAO" 
   (	"ID_TURNO" NUMBER(*,0), 
	"ID_CENTRO" NUMBER(*,0), 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"TEMPO_MEDIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VACINAS
--------------------------------------------------------

  CREATE TABLE "LEIAABDG10"."VACINAS" 
   (	"ID_VACINA" NUMBER(*,0), 
	"PAIS" VARCHAR2(1024 BYTE), 
	"INTERVALODOSE" NUMBER, 
	"TEMPO_APOS_ABERTURA" NUMBER(*,0), 
	"NOME" VARCHAR2(1024 BYTE), 
	"LABORATORIO" VARCHAR2(1024 BYTE), 
	"DATA_APROVACAO" DATE, 
	"NUM_DOSES" NUMBER(*,0), 
	"CONDICOES" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ABRANGIDAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_ABRANGIDAS" ON "LEIAABDG10"."ABRANGIDAS" ("ID_PROFISSAO", "ID_CRITERIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABRANGIDAS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."ABRANGIDAS_FK" ON "LEIAABDG10"."ABRANGIDAS" ("ID_PROFISSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ABRANGIDAS2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."ABRANGIDAS2_FK" ON "LEIAABDG10"."ABRANGIDAS" ("ID_CRITERIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ARMAZENS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_ARMAZENS" ON "LEIAABDG10"."ARMAZENS" ("ID_ARMAZEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CAUSAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_CAUSAM" ON "LEIAABDG10"."CAUSAM" ("ID_TOMA", "ID_REACOES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CAUSAM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."CAUSAM_FK" ON "LEIAABDG10"."CAUSAM" ("ID_TOMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CAUSAM2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."CAUSAM2_FK" ON "LEIAABDG10"."CAUSAM" ("ID_REACOES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CENTRO_SAUDE
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_CENTRO_SAUDE" ON "LEIAABDG10"."CENTRO_SAUDE" ("ID_CENTROSAUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CENTROS_VACINACAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_CENTROS_VACINACAO" ON "LEIAABDG10"."CENTROS_VACINACAO" ("ID_CENTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CONVOCATORIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_CONVOCATORIAS" ON "LEIAABDG10"."CONVOCATORIAS" ("ID_CONVOCATORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ENVIAM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."ENVIAM_FK" ON "LEIAABDG10"."CONVOCATORIAS" ("CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESULTAM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."RESULTAM_FK" ON "LEIAABDG10"."CONVOCATORIAS" ("ID_FASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."TEM_FK" ON "LEIAABDG10"."CONVOCATORIAS" ("ID_SLOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CRITERIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_CRITERIOS" ON "LEIAABDG10"."CRITERIOS" ("ID_CRITERIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERTENCEM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PERTENCEM_FK" ON "LEIAABDG10"."CRITERIOS" ("ID_FASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DOENCAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_DOENCAS" ON "LEIAABDG10"."DOENCAS" ("ID_DOENCAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PROVEM_FK" ON "LEIAABDG10"."DOENCAS" ("ID_CRITERIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DOSES
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_DOSES" ON "LEIAABDG10"."DOSES" ("ID_DOSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RETIRADAS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."RETIRADAS_FK" ON "LEIAABDG10"."DOSES" ("ID_FRASCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ENFERMEIROS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_ENFERMEIROS" ON "LEIAABDG10"."ENFERMEIROS" ("CC", "ID_ENFERMEIRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PODEM_SER_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PODEM_SER_FK" ON "LEIAABDG10"."ENFERMEIROS" ("CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EXERCEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_EXERCEM" ON "LEIAABDG10"."EXERCEM" ("ID_PROFISSAO", "CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXERCEM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."EXERCEM_FK" ON "LEIAABDG10"."EXERCEM" ("ID_PROFISSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXERCEM2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."EXERCEM2_FK" ON "LEIAABDG10"."EXERCEM" ("CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FASES
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_FASES" ON "LEIAABDG10"."FASES" ("ID_FASE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FRASCOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_FRASCOS" ON "LEIAABDG10"."FRASCOS" ("ID_FRASCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERTENCENTES_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PERTENCENTES_FK" ON "LEIAABDG10"."FRASCOS" ("ID_LOTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LEVAM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."LEVAM_FK" ON "LEIAABDG10"."FRASCOS" ("ID_TRANSPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INCLUEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_INCLUEM" ON "LEIAABDG10"."INCLUEM" ("ID_CRITERIOS", "ID_LOCALPROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INCLUEM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."INCLUEM_FK" ON "LEIAABDG10"."INCLUEM" ("ID_CRITERIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INCLUEM2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."INCLUEM2_FK" ON "LEIAABDG10"."INCLUEM" ("ID_LOCALPROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOCAIS_DE_TRABALHO
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_LOCAIS_DE_TRABALHO" ON "LEIAABDG10"."LOCAIS_DE_TRABALHO" ("ID_LOCALPROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_LOTES_DAS_VACINAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_LOTES_DAS_VACINAS" ON "LEIAABDG10"."LOTES_DAS_VACINAS" ("ID_LOTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DAS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."DAS_FK" ON "LEIAABDG10"."LOTES_DAS_VACINAS" ("ID_VACINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GUARDADOS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."GUARDADOS_FK" ON "LEIAABDG10"."LOTES_DAS_VACINAS" ("ID_ARMAZEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORIGINARAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_ORIGINARAM" ON "LEIAABDG10"."ORIGINARAM" ("ID_REACOES", "ID_VACINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORIGINARAM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."ORIGINARAM_FK" ON "LEIAABDG10"."ORIGINARAM" ("ID_REACOES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORIGINARAM2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."ORIGINARAM2_FK" ON "LEIAABDG10"."ORIGINARAM" ("ID_VACINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PESSOAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_PESSOAS" ON "LEIAABDG10"."PESSOAS" ("CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REGISTRADA_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."REGISTRADA_FK" ON "LEIAABDG10"."PESSOAS" ("ID_CENTROSAUDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PODEM_GUARDAR2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PODEM_GUARDAR2_FK" ON "LEIAABDG10"."PODEM_GUARDAR" ("ID_ARMAZEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PODEM_GUARDAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_PODEM_GUARDAR" ON "LEIAABDG10"."PODEM_GUARDAR" ("ID_VACINA", "ID_ARMAZEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PODEM_GUARDAR_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PODEM_GUARDAR_FK" ON "LEIAABDG10"."PODEM_GUARDAR" ("ID_VACINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PODEM_TER
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_PODEM_TER" ON "LEIAABDG10"."PODEM_TER" ("ID_DOENCAS", "CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PODEM_TER_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PODEM_TER_FK" ON "LEIAABDG10"."PODEM_TER" ("ID_DOENCAS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PODEM_TER2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PODEM_TER2_FK" ON "LEIAABDG10"."PODEM_TER" ("CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROFISSOES
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_PROFISSOES" ON "LEIAABDG10"."PROFISSOES" ("ID_PROFISSAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REACOES
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_REACOES" ON "LEIAABDG10"."REACOES" ("ID_REACOES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RESPONSAVEIS1
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_RESPONSAVEIS1" ON "LEIAABDG10"."RESPONSAVEIS" ("ID_TURNO", "ID_ENFERMEIRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESPONSAVEIS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."RESPONSAVEIS_FK" ON "LEIAABDG10"."RESPONSAVEIS" ("ID_TURNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SLOTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_SLOTS" ON "LEIAABDG10"."SLOTS" ("ID_SLOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTAO_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."ESTAO_FK" ON "LEIAABDG10"."SLOTS" ("ID_TURNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TOMAS_DA_VACINA
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_TOMAS_DA_VACINA" ON "LEIAABDG10"."TOMAS_DA_VACINA" ("ID_TOMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TOMADAS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."TOMADAS_FK" ON "LEIAABDG10"."TOMAS_DA_VACINA" ("ID_DOSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PARA2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PARA2_FK" ON "LEIAABDG10"."TOMAS_DA_VACINA" ("ID_CONVOCATORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRABALHAM
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_TRABALHAM" ON "LEIAABDG10"."TRABALHAM" ("ID_LOCALPROF", "CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRABALHAM_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."TRABALHAM_FK" ON "LEIAABDG10"."TRABALHAM" ("ID_LOCALPROF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRABALHAM2_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."TRABALHAM2_FK" ON "LEIAABDG10"."TRABALHAM" ("CC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TRANSPORTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_TRANSPORTES" ON "LEIAABDG10"."TRANSPORTES" ("ID_TRANSPORTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DOS_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."DOS_FK" ON "LEIAABDG10"."TRANSPORTES" ("ID_ARMAZEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDE_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."PEDE_FK" ON "LEIAABDG10"."TRANSPORTES" ("ID_CENTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TURNOS_DE_VACINACAO
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_TURNOS_DE_VACINACAO" ON "LEIAABDG10"."TURNOS_DE_VACINACAO" ("ID_TURNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOCALIZA_SE_FK
--------------------------------------------------------

  CREATE INDEX "LEIAABDG10"."LOCALIZA_SE_FK" ON "LEIAABDG10"."TURNOS_DE_VACINACAO" ("ID_CENTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VACINAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "LEIAABDG10"."PK_VACINAS" ON "LEIAABDG10"."VACINAS" ("ID_VACINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ABRANGIDAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ABRANGIDAS" ADD CONSTRAINT "PK_ABRANGIDAS" PRIMARY KEY ("ID_PROFISSAO", "ID_CRITERIOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ARMAZENS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ARMAZENS" ADD CONSTRAINT "PK_ARMAZENS" PRIMARY KEY ("ID_ARMAZEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAUSAM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CAUSAM" ADD CONSTRAINT "PK_CAUSAM" PRIMARY KEY ("ID_TOMA", "ID_REACOES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CAUSAM" MODIFY ("ID_TOMA" NOT NULL ENABLE);
 
  ALTER TABLE "LEIAABDG10"."CAUSAM" MODIFY ("ID_REACOES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CENTRO_SAUDE
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CENTRO_SAUDE" ADD CONSTRAINT "PK_CENTRO_SAUDE" PRIMARY KEY ("ID_CENTROSAUDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CENTRO_SAUDE" MODIFY ("ID_CENTROSAUDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CENTROS_VACINACAO
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CENTROS_VACINACAO" ADD CONSTRAINT "PK_CENTROS_VACINACAO" PRIMARY KEY ("ID_CENTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CENTROS_VACINACAO" MODIFY ("ID_CENTRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONVOCATORIAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CONVOCATORIAS" ADD CONSTRAINT "PK_CONVOCATORIAS" PRIMARY KEY ("ID_CONVOCATORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CONVOCATORIAS" MODIFY ("ID_CONVOCATORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CRITERIOS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CRITERIOS" ADD CONSTRAINT "PK_CRITERIOS" PRIMARY KEY ("ID_CRITERIOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CRITERIOS" MODIFY ("ID_CRITERIOS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOENCAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."DOENCAS" ADD CONSTRAINT "PK_DOENCAS" PRIMARY KEY ("ID_DOENCAS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."DOENCAS" MODIFY ("ID_DOENCAS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOSES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."DOSES" ADD CONSTRAINT "PK_DOSES" PRIMARY KEY ("ID_DOSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."DOSES" MODIFY ("ID_DOSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENFERMEIROS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ENFERMEIROS" ADD CONSTRAINT "PK_ENFERMEIROS" PRIMARY KEY ("CC", "ID_ENFERMEIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."ENFERMEIROS" MODIFY ("CC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXERCEM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."EXERCEM" ADD CONSTRAINT "PK_EXERCEM" PRIMARY KEY ("ID_PROFISSAO", "CC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."EXERCEM" MODIFY ("CC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FASES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."FASES" ADD CONSTRAINT "PK_FASES" PRIMARY KEY ("ID_FASE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."FASES" MODIFY ("ID_FASE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FRASCOS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."FRASCOS" ADD CONSTRAINT "PK_FRASCOS" PRIMARY KEY ("ID_FRASCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."FRASCOS" MODIFY ("ID_FRASCO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INCLUEM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."INCLUEM" ADD CONSTRAINT "PK_INCLUEM" PRIMARY KEY ("ID_CRITERIOS", "ID_LOCALPROF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."INCLUEM" MODIFY ("ID_CRITERIOS" NOT NULL ENABLE);
 
  ALTER TABLE "LEIAABDG10"."INCLUEM" MODIFY ("ID_LOCALPROF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCAIS_DE_TRABALHO
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."LOCAIS_DE_TRABALHO" ADD CONSTRAINT "PK_LOCAIS_DE_TRABALHO" PRIMARY KEY ("ID_LOCALPROF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."LOCAIS_DE_TRABALHO" MODIFY ("ID_LOCALPROF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOTES_DAS_VACINAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."LOTES_DAS_VACINAS" ADD CONSTRAINT "PK_LOTES_DAS_VACINAS" PRIMARY KEY ("ID_LOTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."LOTES_DAS_VACINAS" MODIFY ("ID_LOTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORIGINARAM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ORIGINARAM" ADD CONSTRAINT "PK_ORIGINARAM" PRIMARY KEY ("ID_REACOES", "ID_VACINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."ORIGINARAM" MODIFY ("ID_REACOES" NOT NULL ENABLE);
 
  ALTER TABLE "LEIAABDG10"."ORIGINARAM" MODIFY ("ID_VACINA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PESSOAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PESSOAS" ADD CONSTRAINT "PK_PESSOAS" PRIMARY KEY ("CC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."PESSOAS" MODIFY ("CC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PODEM_GUARDAR
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PODEM_GUARDAR" ADD CONSTRAINT "PK_PODEM_GUARDAR" PRIMARY KEY ("ID_VACINA", "ID_ARMAZEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PODEM_TER
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PODEM_TER" ADD CONSTRAINT "PK_PODEM_TER" PRIMARY KEY ("ID_DOENCAS", "CC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."PODEM_TER" MODIFY ("ID_DOENCAS" NOT NULL ENABLE);
 
  ALTER TABLE "LEIAABDG10"."PODEM_TER" MODIFY ("CC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFISSOES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PROFISSOES" ADD CONSTRAINT "PK_PROFISSOES" PRIMARY KEY ("ID_PROFISSAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REACOES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."REACOES" ADD CONSTRAINT "PK_REACOES" PRIMARY KEY ("ID_REACOES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."REACOES" MODIFY ("ID_REACOES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPONSAVEIS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."RESPONSAVEIS" ADD CONSTRAINT "PK_RESPONSAVEIS" PRIMARY KEY ("ID_TURNO", "ID_ENFERMEIRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."RESPONSAVEIS" MODIFY ("ID_TURNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SLOTS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."SLOTS" ADD CONSTRAINT "PK_SLOTS" PRIMARY KEY ("ID_SLOT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."SLOTS" MODIFY ("ID_SLOT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOMAS_DA_VACINA
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TOMAS_DA_VACINA" ADD CONSTRAINT "PK_TOMAS_DA_VACINA" PRIMARY KEY ("ID_TOMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."TOMAS_DA_VACINA" MODIFY ("ID_TOMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRABALHAM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TRABALHAM" ADD CONSTRAINT "PK_TRABALHAM" PRIMARY KEY ("ID_LOCALPROF", "CC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSPORTES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TRANSPORTES" ADD CONSTRAINT "PK_TRANSPORTES" PRIMARY KEY ("ID_TRANSPORTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TURNOS_DE_VACINACAO
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TURNOS_DE_VACINACAO" ADD CONSTRAINT "PK_TURNOS_DE_VACINACAO" PRIMARY KEY ("ID_TURNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."TURNOS_DE_VACINACAO" MODIFY ("ID_TURNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VACINAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."VACINAS" ADD CONSTRAINT "PK_VACINAS" PRIMARY KEY ("ID_VACINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "LEIAABDG10"."VACINAS" MODIFY ("ID_VACINA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ABRANGIDAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ABRANGIDAS" ADD CONSTRAINT "FK_ABRANGID_ABRANGIDA_CRITERIO" FOREIGN KEY ("ID_CRITERIOS")
	  REFERENCES "LEIAABDG10"."CRITERIOS" ("ID_CRITERIOS") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."ABRANGIDAS" ADD CONSTRAINT "FK_ABRANGID_ABRANGIDA_PROFISSO" FOREIGN KEY ("ID_PROFISSAO")
	  REFERENCES "LEIAABDG10"."PROFISSOES" ("ID_PROFISSAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAUSAM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CAUSAM" ADD CONSTRAINT "FK_CAUSAM_CAUSAM2_REACOES" FOREIGN KEY ("ID_REACOES")
	  REFERENCES "LEIAABDG10"."REACOES" ("ID_REACOES") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CAUSAM" ADD CONSTRAINT "FK_CAUSAM_CAUSAM_TOMAS_DA" FOREIGN KEY ("ID_TOMA")
	  REFERENCES "LEIAABDG10"."TOMAS_DA_VACINA" ("ID_TOMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONVOCATORIAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CONVOCATORIAS" ADD CONSTRAINT "FK_CONVOCAT_ENVIAM_PESSOAS" FOREIGN KEY ("CC")
	  REFERENCES "LEIAABDG10"."PESSOAS" ("CC") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CONVOCATORIAS" ADD CONSTRAINT "FK_CONVOCAT_RESULTAM_FASES" FOREIGN KEY ("ID_FASE")
	  REFERENCES "LEIAABDG10"."FASES" ("ID_FASE") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."CONVOCATORIAS" ADD CONSTRAINT "FK_CONVOCAT_TEM_SLOTS" FOREIGN KEY ("ID_SLOT")
	  REFERENCES "LEIAABDG10"."SLOTS" ("ID_SLOT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CRITERIOS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."CRITERIOS" ADD CONSTRAINT "FK_CRITERIO_PERTENCEM_FASES" FOREIGN KEY ("ID_FASE")
	  REFERENCES "LEIAABDG10"."FASES" ("ID_FASE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOENCAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."DOENCAS" ADD CONSTRAINT "FK_DOENCAS_PROVEM_CRITERIO" FOREIGN KEY ("ID_CRITERIOS")
	  REFERENCES "LEIAABDG10"."CRITERIOS" ("ID_CRITERIOS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOSES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."DOSES" ADD CONSTRAINT "FK_DOSES_RETIRADAS_FRASCOS" FOREIGN KEY ("ID_FRASCO")
	  REFERENCES "LEIAABDG10"."FRASCOS" ("ID_FRASCO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENFERMEIROS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ENFERMEIROS" ADD CONSTRAINT "FK_ENFERMEI_PODEM_SER_PESSOAS" FOREIGN KEY ("CC")
	  REFERENCES "LEIAABDG10"."PESSOAS" ("CC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXERCEM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."EXERCEM" ADD CONSTRAINT "FK_EXERCEM_EXERCEM2_PESSOAS" FOREIGN KEY ("CC")
	  REFERENCES "LEIAABDG10"."PESSOAS" ("CC") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."EXERCEM" ADD CONSTRAINT "FK_EXERCEM_EXERCEM_PROFISSO" FOREIGN KEY ("ID_PROFISSAO")
	  REFERENCES "LEIAABDG10"."PROFISSOES" ("ID_PROFISSAO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FRASCOS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."FRASCOS" ADD CONSTRAINT "FK_FRASCOS_LEVAM_TRANSPOR" FOREIGN KEY ("ID_TRANSPORTE")
	  REFERENCES "LEIAABDG10"."TRANSPORTES" ("ID_TRANSPORTE") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."FRASCOS" ADD CONSTRAINT "FK_FRASCOS_PERTENCEN_LOTES_DA" FOREIGN KEY ("ID_LOTE")
	  REFERENCES "LEIAABDG10"."LOTES_DAS_VACINAS" ("ID_LOTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INCLUEM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."INCLUEM" ADD CONSTRAINT "FK_INCLUEM_INCLUEM2_LOCAIS_D" FOREIGN KEY ("ID_LOCALPROF")
	  REFERENCES "LEIAABDG10"."LOCAIS_DE_TRABALHO" ("ID_LOCALPROF") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."INCLUEM" ADD CONSTRAINT "FK_INCLUEM_INCLUEM_CRITERIO" FOREIGN KEY ("ID_CRITERIOS")
	  REFERENCES "LEIAABDG10"."CRITERIOS" ("ID_CRITERIOS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOTES_DAS_VACINAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."LOTES_DAS_VACINAS" ADD CONSTRAINT "FK_LOTES_DA_DAS_VACINAS" FOREIGN KEY ("ID_VACINA")
	  REFERENCES "LEIAABDG10"."VACINAS" ("ID_VACINA") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."LOTES_DAS_VACINAS" ADD CONSTRAINT "FK_LOTES_DA_GUARDADOS_ARMAZENS" FOREIGN KEY ("ID_ARMAZEM")
	  REFERENCES "LEIAABDG10"."ARMAZENS" ("ID_ARMAZEM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORIGINARAM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."ORIGINARAM" ADD CONSTRAINT "FK_ORIGINAR_ORIGINARA_REACOES" FOREIGN KEY ("ID_REACOES")
	  REFERENCES "LEIAABDG10"."REACOES" ("ID_REACOES") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."ORIGINARAM" ADD CONSTRAINT "FK_ORIGINAR_ORIGINARA_VACINAS" FOREIGN KEY ("ID_VACINA")
	  REFERENCES "LEIAABDG10"."VACINAS" ("ID_VACINA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PESSOAS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PESSOAS" ADD CONSTRAINT "FK_PESSOAS_REGISTRAD_CENTRO_S" FOREIGN KEY ("ID_CENTROSAUDE")
	  REFERENCES "LEIAABDG10"."CENTRO_SAUDE" ("ID_CENTROSAUDE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PODEM_GUARDAR
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PODEM_GUARDAR" ADD CONSTRAINT "FK_PODEM_GU_PODEM_GUA_ARMAZENS" FOREIGN KEY ("ID_ARMAZEM")
	  REFERENCES "LEIAABDG10"."ARMAZENS" ("ID_ARMAZEM") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."PODEM_GUARDAR" ADD CONSTRAINT "FK_PODEM_GU_PODEM_GUA_VACINAS" FOREIGN KEY ("ID_VACINA")
	  REFERENCES "LEIAABDG10"."VACINAS" ("ID_VACINA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PODEM_TER
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."PODEM_TER" ADD CONSTRAINT "FK_PODEM_TE_PODEM_TER_DOENCAS" FOREIGN KEY ("ID_DOENCAS")
	  REFERENCES "LEIAABDG10"."DOENCAS" ("ID_DOENCAS") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."PODEM_TER" ADD CONSTRAINT "FK_PODEM_TE_PODEM_TER_PESSOAS" FOREIGN KEY ("CC")
	  REFERENCES "LEIAABDG10"."PESSOAS" ("CC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPONSAVEIS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."RESPONSAVEIS" ADD CONSTRAINT "FK_RESPONSA_RESPONSAV_TURNOS_D" FOREIGN KEY ("ID_TURNO")
	  REFERENCES "LEIAABDG10"."TURNOS_DE_VACINACAO" ("ID_TURNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SLOTS
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."SLOTS" ADD CONSTRAINT "FK_SLOTS_ESTAO_TURNOS_D" FOREIGN KEY ("ID_TURNO")
	  REFERENCES "LEIAABDG10"."TURNOS_DE_VACINACAO" ("ID_TURNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOMAS_DA_VACINA
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TOMAS_DA_VACINA" ADD CONSTRAINT "FK_TOMAS_DA_PARA2_CONVOCAT" FOREIGN KEY ("ID_CONVOCATORIA")
	  REFERENCES "LEIAABDG10"."CONVOCATORIAS" ("ID_CONVOCATORIA") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."TOMAS_DA_VACINA" ADD CONSTRAINT "FK_TOMAS_DA_TOMADAS_DOSES" FOREIGN KEY ("ID_DOSE")
	  REFERENCES "LEIAABDG10"."DOSES" ("ID_DOSE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRABALHAM
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TRABALHAM" ADD CONSTRAINT "FK_TRABALHA_TRABALHAM_LOCAIS_D" FOREIGN KEY ("ID_LOCALPROF")
	  REFERENCES "LEIAABDG10"."LOCAIS_DE_TRABALHO" ("ID_LOCALPROF") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."TRABALHAM" ADD CONSTRAINT "FK_TRABALHA_TRABALHAM_PESSOAS" FOREIGN KEY ("CC")
	  REFERENCES "LEIAABDG10"."PESSOAS" ("CC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSPORTES
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TRANSPORTES" ADD CONSTRAINT "FK_TRANSPOR_DOS_ARMAZENS" FOREIGN KEY ("ID_ARMAZEM")
	  REFERENCES "LEIAABDG10"."ARMAZENS" ("ID_ARMAZEM") ENABLE;
 
  ALTER TABLE "LEIAABDG10"."TRANSPORTES" ADD CONSTRAINT "FK_TRANSPOR_PEDE_CENTROS_" FOREIGN KEY ("ID_CENTRO")
	  REFERENCES "LEIAABDG10"."CENTROS_VACINACAO" ("ID_CENTRO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TURNOS_DE_VACINACAO
--------------------------------------------------------

  ALTER TABLE "LEIAABDG10"."TURNOS_DE_VACINACAO" ADD CONSTRAINT "FK_TURNOS_D_LOCALIZA__CENTROS_" FOREIGN KEY ("ID_CENTRO")
	  REFERENCES "LEIAABDG10"."CENTROS_VACINACAO" ("ID_CENTRO") ENABLE;
